name: Github Pages Deployment

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: deploy GH pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Git
        run: git config user.name joeyiming && git config user.email 57522684+joeyiming@users.noreply.github.com
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm i, build and test
        run: |
          npm i
          npm run build --if-present
          npm test      
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

